import React from "react";
import Submarine from "../../Assets/Images/submarine.jpeg";
import Krane from "../../Assets/Images/krane.jpeg";
import GreenWroker from "../../Assets/Images/green worker.jpeg";
import GreenKrane from "../../Assets/Images/green_crane.png";
import Etihad from "../../Assets/Images/etihad.jpeg";

const MainBottom = () => {
  return (
    <div className="bg-greyBackground rounded-4xl p-4">
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 items-center">
        <div className="lg:col-span-1">
          <img src={Submarine} alt="submarine" className="rounded-3xl" />
        </div>
        <div className="text-center lg:col-span-2 lg:text-start ">
          <ol>
            <li>
              <strong>ABoS</strong> is continually maintaining a highly
              qualified inspection and consultancy team, employing the latest
              technical expertise and paraphernalia, stressing utmost importance
              in safety, environment, quality, and timely completion task, and
              complying with all local & international regulations.
            </li>
            <li className="py-4">
              <strong>ABoS</strong> is continually maintaining a highly
              qualified inspection and consultancy team, employing the latest
              technical expertise and paraphernalia, stressing utmost importance
              in safety, environment, quality, and timely completion task, and
              complying with all local & international regulations.
            </li>

            <li>
              <strong>ABOS</strong> is providing inspection services according
              to proven methods for inspection based on guidelines and Standard
              Operating Procedure. The Inspection and consultancy team is well
              organized by our Technical Manager & Training Manager and doing
              the task as per his authorization. is providing inspection
              services according to proven methods for inspection based on
              guidelines and Standard Operating Procedure. The Inspection and
              consultancy team is well organized by our Technical Manager &
              Training Manager and doing the task as per his authorization.
            </li>
          </ol>
        </div>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 justify-start items-start">
        <div className="text-center p-4 bg-red-200">
          <img src={Krane} alt="krane" className="rounded-3xl h-full" />
          <div>
            <h1 className="text-darkBlue font-bold pt-2">Office Facilities</h1>
            <p className="text-center lg:text-start">
              <strong>ABOS’s Abu Dhabi office</strong> is located in the heart of
              the city & the operations will be handled at Mussafah offices to
              serve the clients at anytime during the business hours. The
              communication between the departments and personals are established
              through phone, e-mails, & verbal conversations.All the Certificates
              and reports are generated by the engineers to avoid delays & errors
              to ensure the trust of the customer
            </p>
          </div>
        </div>

        <div className="text-center p-4 bg-red-200">
          <img
            src={GreenWroker}
            alt="Green Worker"
            className="rounded-3xl max-h-11/12"
          />
          <h1 className="text-darkBlue font-bold pt-2">Work Experience</h1>
          <p className="text-center lg:text-start">
            We ABoS work with various prestigious projects with well reputed
            companies in UAE such as ADNATCO, NMDC, SMG, IMCC group (GPC, IMAC,
            GSME, CIC, ADCE), GS Engineering, Hyundai, Galfar Engineering, AL
            Sahraa. We can listed various projects which we handled by us on
            request
          </p>
        </div>

        <div className="text-center p-4 bg-red-200">
          <img
            src={GreenKrane}
            alt="Green Krane"
            className="rounded-3xl max-h-11/12"
          />
          <h1 className="text-darkBlue font-bold pt-2">Quality & HSE</h1>
          <p className="text-center lg:text-start">
            ABoS is committed with High level of standardization with Quality &
            HSE. Our Company is certified by LEEA & ENAS for our inspection
            activities as per iso17020:2012 & our EHSMS system is recently
            certified by RINA Services for ISO14001:2004: ISO 18001:2007.
          </p>
        </div>

        <div className="text-center p-4 bg-red-200">
          <img src={Etihad} alt="Etihad" className="rounded-3xl" />
          <h1 className="text-darkBlue font-bold pt-2">Over all highlights</h1>
          <p className="text-center lg:text-start">
            We are the well-known and reputed company in UAE for the inspection
            and training activities over two decades. We have the approval with
            ADCO, ADMA, ZADCO, TAKREER, Al HOSN GAS; GASCO; BURAGE, FERTIL, Etc.
          </p>
        </div>
      </div>
    </div>
  );
};

export default MainBottom;
